export const UPDATE_ROUTES = 'UPDATE_ROUTES';
export const UPDATE_ROUTE = 'UPDATE_ROUTE';
export const ROUTE_CREATED = 'ROUTE_CREATED';
export const ROUTE_SAVED = 'ROUTE_SAVED';
export const ROUTE_DELETED = 'ROUTE_DELETED';
export const ROUTE_DIALOG_OPEN = 'ROUTE_DIALOG_OPEN';
export const ROUTE_DIALOG_CLOSE = 'ROUTE_DIALOG_CLOSE';

export const UPDATE_ACTIONS = 'UPDATE_ACTIONS';
export const UPDATE_ACTION = 'UPDATE_ACTION';
export const ACTION_CREATED = 'ACTION_CREATED';
export const ACTION_SAVED = 'ACTION_SAVED';
export const ACTION_DELETED = 'ACTION_DELETED';
export const ACTION_DIALOG_OPEN = 'ACTION_DIALOG_OPEN';
export const ACTION_DIALOG_CLOSE = 'ACTION_DIALOG_CLOSE';

export const UPDATE_LOCATION_GROUPS = 'UPDATE_LOCATION_GROUPS';